name: build-dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION_PATH: ./src/HebrewAcronymUtil/HebrewAcronymUtil.sln

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal