name: Deploy to NuGet

on: workflow_dispatch

env:
  SOLUTION_PATH: ./src/HebrewAcronymUtil/HebrewAcronymUtil.sln
  NUGET_PACKAGE_PATH: .\src\HebrewAcronymUtil\HebrewAcronymUtil\HebrewAcronymUtil.csproj

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal

      - name: Pack
        run: dotnet pack ${{ env.NUGET_PACKAGE_PATH }} --configuration Release --no-build --output nupkgs

      - name: Push to NuGet
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json